services:

  pingfederate:
    image: pingfedonetap/pingfederate:${PINGFEDERATE_IMAGE_TAG:-2511-12.3.3}
    build:
      context: ./docker
      dockerfile: pingfederate/Dockerfile
      args:
        PINGFEDERATE_IMAGE_TAG: ${PINGFEDERATE_IMAGE_TAG:-2511-12.3.3}
    container_name: pingfederate-xaa
    environment:
      PING_IDENTITY_ACCEPT_EULA: "YES"
      PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
      PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
      SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
      SERVER_PROFILE_PATH: getting-started/pingfederate
    ports:
      - "9999:9999"
      - "9031:9031"
    volumes:
      - pingfederate-out:/opt/out
    tmpfs:
      - /run/secrets

volumes:
  pingfederate-out:
